### ISSUE TITLE
Test doesn't run on aws devices farm

### ISSUE THREAD

**Issue by YaroslavHavrylovych** [aws-samples/aws-device-farm-appium-tests-for-sample-app#18] opened 2018-05-09 08:44 UTC
I did pull the appium-tests-for-sample-app project, 
and generated zip-with-dependencies.zip (i.e. typed `mvn clean package -DskipTests=true`).

I generated apk for [sample-app](https://github.com/aws-samples/aws-device-farm-sample-app-for-android) and checked it worked on my device.

Add the apk to aws-farm, added tests as testng and run. Always same results: setup suite and teardown suite are done, the rest - failed. On the video from device farm I can see that the app didn't start at all. I tried even an empty test and same.

I can't find anything usefull in the logs.

Locally appium works fine. I had a lot of tests to run, but can't make it work in cloud.

I'm searching for the help or for any new idea (I spent the whole day on trying to run it).

Test results:

<img width="983" alt="screen shot 2018-05-09 at 10 35 28" src="https://user-images.githubusercontent.com/2469733/39804907-08c6be5c-537e-11e8-91e4-8eaab0cf285f.png">

**Comment by floorra** [comment] 2018-05-17 22:55
Hi,

Can you share your failed run url with us, so we can help you debug it.

**Comment by jamesknowsbest** [comment] 2018-05-24 17:32
Did you check your desired capabilities. What may have happened is that they're set for the local execution. We shouldn't need to set these for device farm as it will do that on our behalf if that is the case. Let me know either way when you get the chance.

**Comment by YaroslavHavrylovych** [comment] 2018-05-24 20:38
I used empty capabilities (as [here](https://github.com/aws-samples/aws-device-farm-appium-tests-for-sample-app/blob/master/src/test/java/Tests/AbstractBaseTests/TestBase.java)):
```
DesiredCapabilities capabilities = new DesiredCapabilities();
driver = new AndroidDriver<MobileElement>("http://127.0.0.1:4723/wd/hub", capabilities);
```
and once tried with device set `capabilities.setCapability("deviceName", "Android");`
Is that what you're asking @jamesknowsbest ?

**Comment by YaroslavHavrylovych** [comment] 2018-05-24 20:41
Sorry, @floorra but how can I share a url with you? I doubt you access a link even if I would post it here. Or maybe you meant something else?

**Comment by jamesknowsbest** [comment] 2018-05-24 20:42
@YaroslavHavrylovych  yes, which device are you using? I want to try and reproduce the issue. Also @floorra I assume works for the device farm team or some derivative of. I believe they can use the GUIDs in the URL to look up the logs and see what the issues was.

**Comment by YaroslavHavrylovych** [comment] 2018-05-24 20:53
So device is "amazon fire 2015".
 
The simplest test link is [here](https://us-west-2.console.aws.amazon.com/devicefarm/home?region=eu-west-1#/projects/3e163a0f-15d4-413f-8952-cdae0111c3e9/runs/c6aac1a0-f6e4-46f5-ae99-30a9251fa365).

Thanks for your time.

**Comment by jamesknowsbest** [comment] 2018-05-24 21:14
Okay, 

I cloned the and built the sample project using these commands: 
 ```
git clone https://github.com/awslabs/aws-device-farm-sample-app-for-android.git
    cd aws-device-farm-sample-app-for-android/
    ./gradlew cC
```

Then I build the sample project here using these commands: 

```
git clone https://github.com/awslabs/aws-device-farm-appium-tests-for-sample-app.git
cd aws-device-farm-appium-tests-for-sample-app/
mvn clean package -DskipTests=true
```
Then I scheduled a run with appium 1.7.2 and the amazon file 2015
![image](https://user-images.githubusercontent.com/32966786/40513671-79e926c2-5f74-11e8-8c74-1b8f3aa8e91c.png)

![image](https://user-images.githubusercontent.com/32966786/40513568-2c9bd6ee-5f74-11e8-84f2-7f92c967527b.png)

![image](https://user-images.githubusercontent.com/32966786/40513760-bd60ab8c-5f74-11e8-96cc-0f4528a5308f.png)

and I can reproduce the issue.

![image](https://user-images.githubusercontent.com/32966786/40513978-80bf4f48-5f75-11e8-9565-0339271d2523.png)

It looks like there is an issue with that device from the logs

![image](https://user-images.githubusercontent.com/32966786/40514019-aef9c10e-5f75-11e8-8a88-2b66ed1b39f1.png)

Here is my URL

https://us-west-2.console.aws.amazon.com/devicefarm/home?region=us-east-1#/projects/3141c0a7-8f38-4099-a679-00e7a9a5e46c/runs/d1111cb3-9549-4343-96fd-585f068beb95/jobs/00000/suites/00001

I'm running the same test on the google pixel 7.1.2 to see if they work there.

**Comment by floorra** [comment] 2018-05-24 22:15
Hi,

This is a known issue only with amazon fire 2015 device. We are working on fix for this issue. Please try other devices. You should be able to run your tests.

Thanks

**Comment by rekha110254** [comment] 2018-05-25 15:02
Hi!
Device farm creating new appium instance for each test case in testng.xml. How can i control it?

I want to run all test classes in sequence without creating new instance

**Closed** 2018-06-07 09:43 UTC
